config/routes.rb
Rails.application.routes.draw do


  get "/search" => 'searches#search'
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'homes#top'   
  get "home/about" => "homes#about"
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :books_comments, only: [:create, :destroy]  
    resource :favorites, only: [:create, :destroy]  

    
  end
     
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
 resources :users, only: [:show,:edit,:update,:index] do
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]   
    resource :relationships, only: [:create, :destroy]      
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end
 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :books_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end    

    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/books_comment.rb
class BooksComment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book    
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy    
  has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books_comments, dependent: :destroy
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :entries, dependent: :destroy  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  
  has_many :followings, through: :relationships, source: :followed
  attachment :profile_image  
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: {maximum:50} 
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end  
  def matchers
    followings & followers
  end  

end

app/controllers/books_comments_controller.rb
class BooksCommentsController < ApplicationController
  def create

    @book = Book.find(params[:book_id])
    @books_comment = @book.books_comments.new(books_comment_params)
    @books_comment.user_id = current_user.id
    @books_comment.book_id = @book.id
    @books_comment.save
    render :create
    
  end

  def destroy
    @book = Book.find(params[:book_id])    
    BooksComment.find_by(id: params[:id]).destroy
    render :destroy
  end
  private
  def books_comment_params
    params.require(:books_comment).permit(:comment)
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :index
    end  
  end
  
  def edit
    @book = Book.find(params[:id])
    if current_user == @book.user
      render :edit
    else
      redirect_to books_path
    end  
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end  
  end  

  def index
    @books = Book.all
    @book = Book.new
    @user = @book.user
    @books_comments = BooksComment.all
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day    
    @books = Book.includes(:favorite_users).sort {|a,b|
    b.favorite_users.includes(:favorites).where(created_at: from...to).size <=> a.favorite_users.includes(:favorites).where(created_at: from...to).size}

  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new 
    @user = @book.user
    @books_comment = BooksComment.new
    @books_comments = BooksComment.all
    
    
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end  
end  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end    
  
  def about
  end  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 before_action :authenticate_user!

 def create
   @room = Room.create
   @joinCurrentUser = Entry.create(user_id: current_user.id, room_id: @room.id)
   @joinUser = Entry.create(join_room_params)
   redirect_to room_path(@room.id)
 end

 def show
   @room = Room.find(params[:id])
   if Entry.where(user_id: current_user.id, room_id: @room.id).present?
     @messages = @room.messages
     @message = Message.new
     @Entries = @room.Entries
   else
     redirect_back(fallback_location: root_path)
   end
 end

 private

 def join_room_params
   params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page])
    @books_comments = BooksComment.all
    @currentEntry = Entry.where(user_id: current_user.id)  #current_userが既にルームに参加しているか判断
    @receiveUser = Entry.where(user_id: @user.id)  #他の@userがルームに参加しているか判断
    unless @user.id == current_user.id  #current_userと@userが一致していなければ
      @currentEntry.each do |cu|    #current_userが参加していルームを取り出す
        @receiveUser.each do |u|    #@userが参加しているルームを取り出す
          if cu.room_id == u.room_id    #current_userと@userのルームが同じか判断(既にルームが作られているか)
            @haveRoom = true    #falseの時(同じじゃない時)の条件を記述するために変数に代入
            @roomId = cu.room_id   #ルームが共通しているcurrent_userと@userに対して変数を指定
          end
        end
      end
      unless @haveroom    #ルームが同じじゃなければ
        #新しいインスタンスを生成
        @room = Room.new
        @Entry = Entry.new
        #//新しいインスタンスを生成
      end
    end    

  end
  def edit
    @user = User.find(params[:id])
    if current_user == @user
      render :edit
    else
      redirect_to user_path(current_user)
    end
      
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end  
  end
  
  def index
    @users = User.all
    @book = Book.new 
    
  
  end  

  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_comments_helper.rb
module BooksCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books_comments/_book_detail.html.erb
            <table class="table">
              <tbody>
                  <tr>
                    <td>
                      <%= attachment_image_tag book.user, :profile_image,format:'jpeg',fallback:"no_image.jpg", size:"40x40" %></br>
                      <%= link_to user_path(book.user) do %>
                        <%= book.user.name %>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to book_path(book) do %>
                        <%= book.title %>
                      <% end %>                      
                    </td>
                    <td><%= book.body %></td>
                    <% if user_signed_in? && current_user.id == book.user_id %>  
                      <td><%= link_to "Edit", edit_book_path(book),class:"btn btn-success" %></td>
                      <td><%= link_to "Destroy", book_path(book), method: :delete , class:"btn btn-danger" %></td>   
                    <% else %>
                      <td id="favorite_buttons_<%= book.id %>">
                       <%= render "favorites/favorites" , book: book %>
                      </td>                    
                      <td>コメント数:<%= book.books_comments.count %></td>
                    <% end %>
                  </tr>
              </tbody>
            </table>

app/views/books_comments/_comment.html.erb
<table>  
  <tbody>
    <% book.books_comments.each do |books_comment| %>
    <tr>
        <td><%= attachment_image_tag book.user, :profile_image,format:'jpeg',fallback:"no_image.jpg", size:"40x40" %></br>
        <%= link_to user_path(book.user) do %>
        <%= book.user.name %>
        <% end %>                  
        </td>
        <td><%= books_comment.comment %></td>
        <% if current_user == books_comment.user %>
        <td><%= link_to "Destroy", book_books_comment_path(books_comment.book,books_comment), method: :delete , class:"js-delete-comment-button btn btn-danger", remote: true  %></td>
        <% end %>
    </tr>
    <% end %> 
  </tbody>    
</table>    

app/views/books_comments/_comment_form.html.erb
<%= form_with(model:[book, books_comment],class: "js-form") do |f| %>
    <%= f.text_area :comment, rows:'5',autofocus: true, class: "form-control" %>
    <%= f.submit "送信" %>
<% end %> 

app/views/books_comments/create.js.erb
$("#comments_area").html("<%= j(render 'comment', { book: @book }) %>")
$("textarea").val('')
$("#book_detail").html("<%= j(render "book_detail", { book: @book }) %>")

app/views/books_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'comment', { book: @book }) %>")
$("#book_detail").html("<%= j(render "book_detail", { book: @book }) %>")