config/routes.rb
Rails.application.routes.draw do


  get "/search" => 'searches#search'
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'homes#top'   
  get "home/about" => "homes#about"
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :books_comments, only: [:create, :destroy]  
    resource :favorites, only: [:create, :destroy]  

    
  end
     
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
 resources :users, only: [:show,:edit,:update,:index] do
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]   
    resource :relationships, only: [:create, :destroy]      
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end
 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :books_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end    

    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/books_comment.rb
class BooksComment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book    
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy    
  has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books_comments, dependent: :destroy
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :entries, dependent: :destroy  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  
  has_many :followings, through: :relationships, source: :followed
  attachment :profile_image  
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: {maximum:50} 
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end  
  def matchers
    followings & followers
  end  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :index
    end  
  end
  
  def edit
    @book = Book.find(params[:id])
    if current_user == @book.user
      render :edit
    else
      redirect_to books_path
    end  
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end  
  end  

  def index
    @books = Book.all
    @book = Book.new
    @user = @book.user
    @books_comments = BooksComment.all
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day    
    @books = Book.includes(:favorite_users).sort {|a,b|
    b.favorite_users.includes(:favorites).where(created_at: from...to).size <=> a.favorite_users.includes(:favorites).where(created_at: from...to).size}

  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new 
    @user = @book.user
    @books_comment = BooksComment.new
    @books_comments = BooksComment.all
    
    
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end  
end  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end    
  
  def about
  end  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 before_action :authenticate_user!

 def create
   @room = Room.create
   @joinCurrentUser = Entry.create(user_id: current_user.id, room_id: @room.id)
   @joinUser = Entry.create(join_room_params)
   redirect_to room_path(@room.id)
 end

 def show
   @room = Room.find(params[:id])
   if Entry.where(user_id: current_user.id, room_id: @room.id).present?
     @messages = @room.messages
     @message = Message.new
     @Entries = @room.Entries
   else
     redirect_back(fallback_location: root_path)
   end
 end

 private

 def join_room_params
   params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page])
    @books_comments = BooksComment.all
    @currentEntry = Entry.where(user_id: current_user.id)  #current_userが既にルームに参加しているか判断
    @receiveUser = Entry.where(user_id: @user.id)  #他の@userがルームに参加しているか判断
    unless @user.id == current_user.id  #current_userと@userが一致していなければ
      @currentEntry.each do |cu|    #current_userが参加していルームを取り出す
        @receiveUser.each do |u|    #@userが参加しているルームを取り出す
          if cu.room_id == u.room_id    #current_userと@userのルームが同じか判断(既にルームが作られているか)
            @haveRoom = true    #falseの時(同じじゃない時)の条件を記述するために変数に代入
            @roomId = cu.room_id   #ルームが共通しているcurrent_userと@userに対して変数を指定
          end
        end
      end
      unless @haveroom    #ルームが同じじゃなければ
        #新しいインスタンスを生成
        @room = Room.new
        @Entry = Entry.new
        #//新しいインスタンスを生成
      end
    end    

  end
  def edit
    @user = User.find(params[:id])
    if current_user == @user
      render :edit
    else
      redirect_to user_path(current_user)
    end
      
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end  
  end
  
  def index
    @users = User.all
    @book = Book.new 
    
  
  end  

  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_comments_helper.rb
module BooksCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
          <% if @book.errors.any? %>
            <h3 class="text-danger"><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li class="text-danger"><%= message %></li>
            <% end %>
            </ul>
          <% end %>          
          <%= form_with model:@book, local:true do |f| %>
            <div class="form-group">
              <%= f.label :Title %>
              <%= f.text_field :title, autofocus: true, id:"inputTitle", class:"form-control" %>
            </div>  
            <div class="form-group">  
              <%= f.label :Opinion %>
              <%= f.text_area :body, autofocus: true, id:"inputBody", class:"form-control" %>
            </div>  
            <div class="form-group">  
              <%= f.submit "Update Book", class:"btn btn-success" %>
            </div>  
          <% end %>
          <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>          
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
    <div class="container px-5 px-sm-0">
      <% if @book.errors.any? %>
        <h3 class="text-danger"><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>     
        <% @book.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
        </ul>         
      <% end %>        
        <div class="row">
          <div class="col-md-3">
            <%= render "users/user_info", book:@book %>
          </div>
          <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th></th>
                  <th></th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @books.each do |book| %>  
                    <tr>
                      <td><%= link_to user_path(book.user) do %><%= attachment_image_tag book.user, :profile_image,fallback:"no_image.jpg", format: 'jpeg', size: "40x40" %><% end %></td>
                      <td><%= link_to book_path(book) do %><%= book.title %><% end %></td>
                      <td><%= book.body %></td>
                      <td id="favorite_buttons_<%= book.id %>">  
                        <%= render "favorites/favorites" , book: book %>
                      </td>
                      <td>コメント数:<%= book.books_comments.count %></td>
                      <td colspan="3"></td>
                    </tr> 
                <% end %>    
              </tbody>
            </table>
          </div>  
        </div>
    </div>
</main>        

app/views/books/show.html.erb
<main>
    <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">
            <%= render "users/user_info_a", user: @book.user, book: @new_book %>
          </div>
          <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <div id= "book_detail">
              <%= render "books_comments/book_detail", book: @book, user: @user %>
            </div>
            <div id='comments_area'>
              <%= render "books_comments/comment", book: @book ,user: @user %>
            </div>
            <div id="comments_form" >
              <%= render "books_comments/comment_form" ,book: @book, books_comment: @books_comment %>
            </div>  
          </div>
        </div>
    </div>
</main>        

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.email %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/users/_user_info.html.erb
                      <h2>User info</h2>
                        <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', fallback:"no_image.jpg", size:"100x100" %>
                        <table class="table">
                         <tbody>   
                            <tr></tr>
                            <tr>
                                <th>name</th>
                                <th><%= current_user.name %></th>
                            </tr>
                            <tr>
                                <th>introduction</th>
                                <th><%= current_user.introduction %></th>
                            </tr>
                            <tr><th>follows</th><th><%= link_to user_followings_path(current_user) do %><%= current_user.followings.count %><% end %></th></tr>
                            <tr><th>followers</th><th><%= link_to user_followers_path(current_user) do %><%= current_user.followers.count %><% end %></th></tr>
                         </tbody>    
                        </table>
                     <div class="row">
                       <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %>
                       <% end %>                        
                     </div>
                     <h2 class="mt-3">New book</h2>
                     <%= form_with model:book, local:true do |f| %>
                        <div class="form-group">
                          <%= f.label :title %></br>
                          <%= f.text_field :title, class:"form-control book-title" %>
                        </div>  
                        <div class="form-group">  
                          <%= f.label :opinion %></br>
                          <%= f.text_area :body, class:"form-control book-opinion" %>
                        </div>
                        <div class="form-group">
                          <%= f.submit 'Create Book', class:"btn btn-success" do %>
                          <% end %>
                        </div>  
                     <% end %>

app/views/users/_user_info_a.html.erb
                      <h2>User info</h2>
                        <%= attachment_image_tag user, :profile_image,format:'jpeg',fallback:"no_image.jpg", size:"100x100" %>
                        <table class="table">
                         <tbody>   
                            <tr></tr>
                            <tr>
                                <th>name</th>
                                <th><%= user.name %></th>
                            </tr>
                            <tr>
                                <th>introduction</th>
                                <th><%= user.introduction %></th>
                            </tr>
                            <tr><th>follows</th><th><%= link_to user_followings_path(user) do %><%= user.followings.count %><% end %></th></tr>
                            <tr><th>followers</th><th><%= link_to user_followers_path(user) do %><%= user.followers.count %><% end %></th></tr>                           
                         </tbody>    
                        </table>
                     <div class="row">
                      <% if current_user.following?(user) %>
                        <%= link_to user_relationships_path(user.id), class: "btn btn-info  ", method: :delete do %>
                             フォローを外す
                        <% end %> 
                        <% unless user.id == current_user.id %>    #現在ログインしているユーザーではない場合
                           <% if @haveRoom == true %>    #既にルームが作成されている場合は
                             <%= link_to "ダイレクトメッセージ", root_path %>    #そのチャットルームに遷移するボタンを表示
                           <% else %>
                             <%= form_with model: room, local: true do |f|%>    #roomsテーブルに情報を送信
                               <%= fields_for Entry do |r| %>    #room_usersテーブルに情報を送信
                                 <%= r.hidden_field :user_id, value: user.id %>  room_usersテーブルにuser_idを含める
                               <% end %>
                               <%= f.submit "チャットを始める" %>
                             <% end %>
                           <% end %>
                        <% end %>
                      <% else %>
                        <%= link_to user_relationships_path(user.id), class:"btn btn-success ", method: :post do %>
                           フォローする
                        <% end %>                          
                      <% end %>                        
                     </div>
                     <h2 class="mt-3">New book</h2>
                     <%= form_with model:book, local:true do |f| %>
                        <div class="form-group">
                          <%= f.label :title %></br>
                          <%= f.text_field :title, class:"form-control book-title" %>
                        </div>  
                        <div class="form-group">  
                          <%= f.label :opinion %></br>
                          <%= f.text_area :body, class:"form-control book-opinion" %>
                        </div>
                        <div class="form-group">
                          <%= f.submit 'Create Book', class:"btn btn-success" do %>
                          <% end %>
                        </div>
                     <% end %> 

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>User info</h1>
          <% if @user.errors.any? %>
            <h3 class="text-danger"><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li class="text-danger"><%= message %></li>
            <% end %>
            </ul>
          <% end %>  
          <%= form_with model:@user, local:true do |f| %>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control" %>
            </div>  
            <div class="form-group">  
              <%= f.label :image %></br>
              <%= f.attachment_field :profile_image %>
            </div>  
            <div class="form-group">  
              <%= f.label :introduction %>
              <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class:"form-control" %>
            </div>  
            <div class="form-group">  
              <%= f.submit "Update User" , class:"btn btn-success" %>
            </div>  
          <% end %>

      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render "user_info", book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>  
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>  
          </thead>
          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= attachment_image_tag user, :profile_image,format:'jpeg',fallback:"no_image.jpg", size:"40x40" %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followings.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                  <% end %>                  
                </td>
                <td><%= link_to "Show", user_path(user) %></td>
              </tr>
            </tbody>    
          <% end %>
        </table>  
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
    <div class="container px-5 px-sm-0">
      <div class="row">
          <div class="col-md-3">
            <%= render "users/user_info_a", user: @user, book: @book, room:@room, Entry:@Entry ,isRoom:@isRoom %>
          </div>
          <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspam="3"></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @books.each do |book| %>  
                  <tr>
                    <td>
                      <%= link_to user_path(book.user) do %><%= attachment_image_tag book.user, :profile_image,format:'jpeg',fallback:"no_image.jpg", size:"40x40" %><% end %>
                    </td>
                    <td>
                      <%= link_to book_path(book) do %>
                        <%= book.title %>
                      <% end %>                      
                    </td>
                    <td><%= book.body %></td>
                    <td id="favorite_buttons_<%= book.id %>">
                      <%= render "favorites/favorites", book: book %>
                    </td>
                    <td>コメント数:<%= book.books_comments.count %></td>
                  </tr>                
                <% end %>  
              </tbody>
            </table>
          </div>       
      </div>
    </div>
</main>