config/routes.rb
Rails.application.routes.draw do


  get "/search" => 'searches#search'
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :users
  root 'homes#top'   
  get "home/about" => "homes#about"
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resources :books_comments, only: [:create, :destroy]  
    resource :favorites, only: [:create, :destroy]  

    
  end
     
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
 resources :users, only: [:show,:edit,:update,:index] do
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]   
    resource :relationships, only: [:create, :destroy]      
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end
 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :books_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end    

    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/books_comment.rb
class BooksComment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book    
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy    
  has_many :users, through: :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books_comments, dependent: :destroy
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  has_many :entries, dependent: :destroy  
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy  
  has_many :followings, through: :relationships, source: :followed
  attachment :profile_image  
  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: {maximum:50} 
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end  
  def matchers
    followings & followers
  end  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :index
    end  
  end
  
  def edit
    @book = Book.find(params[:id])
    if current_user == @book.user
      render :edit
    else
      redirect_to books_path
    end  
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end  
  end  

  def index
    @books = Book.all
    @book = Book.new
    @user = @book.user
    @books_comments = BooksComment.all
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day    
    @books = Book.includes(:favorite_users).sort {|a,b|
    b.favorite_users.includes(:favorites).where(created_at: from...to).size <=> a.favorite_users.includes(:favorites).where(created_at: from...to).size}

  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new 
    @user = @book.user
    @books_comment = BooksComment.new
    @books_comments = BooksComment.all
    
    
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end  
end  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end    
  
  def about
  end  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
 before_action :authenticate_user!

 def create
   @room = Room.create
   @joinCurrentUser = Entry.create(user_id: current_user.id, room_id: @room.id)
   @joinUser = Entry.create(join_room_params)
   redirect_to room_path(@room.id)
 end

 def show
   @room = Room.find(params[:id])
   if Entry.where(user_id: current_user.id, room_id: @room.id).present?
     @messages = @room.messages
     @message = Message.new
     @Entries = @room.Entries
   else
     redirect_back(fallback_location: root_path)
   end
 end

 private

 def join_room_params
   params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cc6c9ade37.js" crossorigin="anonymous"></script>       
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand"href="/"><span>Bookers</span></a>
            <div class="collpase navbar-collapse">
             <ul class="navbar-nav ml-auto">              
               <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user),class:" fas fa-home nav-link text-light" do %><!--user_path(@user.id)--->
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path,class:"link fas fa-users nav-link text-light" do %>
                  Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path,class:"link fas fa-book-open nav-link text-light" do %>
                  Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path,class:"link fas fa-sign-out-alt nav-link text-light", method: :delete  do%>
                  logout
                  <% end %>
                </li>
               <% else %>
                <li>
                  <%= link_to root_path,class:"link fas fa-home nav-link text-light" do %>
                  Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, class:"link fas fa-link nav-link text-light" do %>
                  About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class:"link fas fa-user-plus nav-link text-light" do %>
                  sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class:"link fas fa-sign-in-alt nav-link text-light" do %>
                  login
                  <% end %>
        　       </li> 
               <% end %>
            </ul>            
          </div>   
        </div>
      </nav>
    </header> 
    <div>
    <% if user_signed_in? %>
      <%= form_with url:search_path, method: :get, local: true do |f| %>
        <%= f.text_field 'search[value]' %>
        <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
        <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
        <%= f.submit :"検索" %>
      <% end %>
    <% end %> 
    </div>  
   <%= yield %>    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>